# ASSERT_CONVENTION: natural_units=dimensionless, jordan_product=(1/2)(ab+ba),
#   octonion_basis=fano_e1e2=e4, complex_structure=u_equals_e7,
#   peirce_decomposition=under_E11,
#   v_half_basis=(x2_0..x2_7,x3_0..x3_7),
#   clifford_signature=Cl(9,0)_gamma_i_sq=+I,
#   clifford_normalization=gamma_1=4*T_b[1]_gamma_k=2*T_b[k]_for_k=2..9
#
# Phase 29, Plan 01: Associative closure, volume element, J_u diagnostics.
#
# Tests for ALGV-03 (observable algebra = M_16(R)) and REPR-01
# (Cl(9,0) representation + J_u Clifford characterization).
#
# References:
#   Lawson-Michelsohn, Spin Geometry (1989), Table I.4.3
#   Krasnov, J. Math. Phys. 62 (2021) 021703, arXiv:1912.11282
#   Boyle, arXiv:2006.16265
#
# Reproducibility: numpy 2.4.2, Python 3.14.2, macOS Darwin 24.6.0

import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'code'))

import numpy as np
import pytest

from octonion_algebra import (
    Octonion, H3O, jordan_product,
    peirce_V1, peirce_Vhalf, peirce_V0,
    Vhalf_basis_vectors, V0_basis_elements,
    compute_T_b_matrices, krasnov_J_u_matrix,
    check_ju_in_span, compute_commutator_algebra,
    rescale_to_clifford_generators,
    compute_associative_closure,
    compute_volume_element,
    compute_ju_anticommutation,
    compute_grade_decomposition,
    find_ju_depth,
    express_ju_as_clifford_polynomial,
    test_ju_uniqueness,
    compute_gsm_commutant,
    verify_spin10_branching,
)

ATOL = 1e-14
ATOL_RANK = 1e-10


# ============================================================================
# Fixtures
# ============================================================================

@pytest.fixture(scope="module")
def T_matrices():
    return compute_T_b_matrices()


@pytest.fixture(scope="module")
def J_u():
    return krasnov_J_u_matrix()


@pytest.fixture(scope="module")
def gamma_matrices(T_matrices):
    return rescale_to_clifford_generators(T_matrices)


@pytest.fixture(scope="module")
def closure_result(T_matrices, J_u):
    return compute_associative_closure(T_matrices, J_u=J_u)


@pytest.fixture(scope="module")
def volume_result(gamma_matrices):
    return compute_volume_element(gamma_matrices)


@pytest.fixture(scope="module")
def anticomm_result(gamma_matrices, J_u):
    return compute_ju_anticommutation(gamma_matrices, J_u)


@pytest.fixture(scope="module")
def grade_result(J_u, gamma_matrices):
    return compute_grade_decomposition(J_u, gamma_matrices)


# ============================================================================
# 1. Associative closure tests
# ============================================================================

class TestAssociativeClosure:
    """Tests for the associative algebra generated by {T_b}."""

    def test_closure_depth_0_is_10(self, closure_result):
        """Dimension at depth 0 = 10 (the 10 generators span a 10-dim space)."""
        assert closure_result['dimensions'][0] == 10

    def test_closure_converges_to_256(self, closure_result):
        """Final dimension = 256 = dim M_16(R).

        This confirms the Cl(9,0) irreducible representation surjects onto
        End(R^16). Benchmark: Lawson-Michelsohn Table I.4.3, Cl(9,0) = M_16(R) + M_16(R),
        so the irrep on R^16 hits all of M_16(R).
        (acceptance test: test-closure-dim-256)
        """
        final_dim = closure_result['dimensions'][-1]
        assert final_dim == 256, f"Expected 256, got {final_dim}"

    def test_closure_monotonic(self, closure_result):
        """Dimensions are non-decreasing at each depth.
        (acceptance test: test-closure-growth)
        """
        dims = closure_result['dimensions']
        for i in range(1, len(dims)):
            assert dims[i] >= dims[i - 1], (
                f"Non-monotonic: depth {i-1}={dims[i-1]} -> depth {i}={dims[i]}")

    def test_closure_growth_sequence(self, closure_result):
        """Verify the dimension growth 10 -> 46 -> 130 -> 256.

        Depth 0: 10 generators.
        Depth 1: 10 + 36 (commutator algebra = spin(9)) = 46.
        Depth 2: 130 (grade 2+3 elements added).
        Depth 3: 256 (full M_16(R)).
        (acceptance test: test-closure-growth)
        """
        dims = closure_result['dimensions']
        assert dims[0] == 10
        assert dims[1] == 46
        assert dims[2] == 130
        assert dims[3] == 256

    def test_closure_contains_identity(self, T_matrices, closure_result):
        """I_{16} is in the closure (4*T_b[0] = I from trace element)."""
        I16 = np.eye(16)
        I_flat = I16.flatten()
        basis = closure_result['basis']
        coeffs, _, _, _ = np.linalg.lstsq(basis, I_flat, rcond=None)
        residual = np.linalg.norm(I_flat - basis @ coeffs)
        assert residual < 1e-12, f"Identity not in closure: residual = {residual}"


# ============================================================================
# 2. Volume element tests
# ============================================================================

class TestVolumeElement:
    """Tests for the Cl(9,0) volume element omega = gamma_1 * ... * gamma_9."""

    def test_volume_element_squared(self, volume_result):
        """omega^2 = I_{16} to machine precision.
        (acceptance test: test-volume-element)
        """
        assert volume_result['omega_squared_error'] < ATOL, (
            f"omega^2 error: {volume_result['omega_squared_error']}")

    def test_volume_element_eigenvalues(self, volume_result):
        """All eigenvalues are +1 (not -1 or mixed).

        For n=9 odd: omega = gamma_1...gamma_9 satisfies omega^2 = +I
        (since (-1)^{9*8/2} = (-1)^{36} = +1). On the irrep, omega = +I or -I.
        The +1 result identifies which simple factor of Cl(9,0) = M_16(R) + M_16(R)
        the representation uses: the P_+ = (1+omega)/2 factor.
        (acceptance test: test-volume-element)
        """
        assert volume_result['which_factor'] in ("+1", "-1"), (
            f"Mixed eigenvalues: {volume_result['eigenvalues']}")
        # The specific sign (+1) is a property of our convention.
        # Either +1 or -1 is valid; what matters is ALL same sign.

    def test_volume_element_commutes_with_generators(self, gamma_matrices, volume_result):
        """omega commutes with all gamma_i (since n=9 is odd).

        For odd n, the volume element is central in Cl(n): omega * gamma_i = gamma_i * omega.
        This is because moving gamma_i through gamma_1...gamma_9 requires passing through
        (n-1) = 8 other generators, picking up (-1)^8 = +1.
        """
        omega = volume_result['omega']
        for i, g in enumerate(gamma_matrices):
            comm = omega @ g - g @ omega
            comm_norm = np.linalg.norm(comm, 'fro')
            assert comm_norm < ATOL, (
                f"[omega, gamma_{i+1}] norm = {comm_norm} (should be 0)")


# ============================================================================
# 3. J_u anticommutation tests
# ============================================================================

class TestJuAnticommutation:
    """Tests for J_u's commutation/anticommutation with Clifford generators."""

    def test_ju_anticommutation_pattern(self, anticomm_result):
        """J_u's relation to each gamma_i is unambiguous: each norm is
        either < 1e-14 (anticommutes/commutes) or > 0.1 (does not).
        No ambiguous cases.
        (acceptance test: test-ju-anticommutation)
        """
        for i, norm in enumerate(anticomm_result['anticommutator_norms']):
            assert norm < 1e-14 or norm > 0.1, (
                f"Ambiguous for gamma_{i+1}: |{{J_u, gamma}}| = {norm}")

    def test_ju_does_not_anticommute_with_all(self, anticomm_result):
        """J_u does NOT anticommute with all 9 gamma_i.

        This means J_u is NOT a '10th Clifford generator' extending Cl(9) to Cl(10).
        The Boyle branching S_{10}^+|_{Spin(9)} = S_9^C does not apply in the
        naive sense of J_u being an additional Clifford generator.
        (acceptance test: test-ju-anticommutation)
        """
        assert not anticomm_result['all_anticommute'], (
            "J_u anticommutes with all gamma_i -- unexpected!")

    def test_ju_commutes_with_gamma_1(self, anticomm_result):
        """J_u commutes with gamma_1 = 4*T_b[1] (diagonal traceless).

        This is because T_b[1] = (1/2)diag(I_8, -I_8) in the (x2, x3) basis,
        and J_u = diag(L_{e7}, L_{e7}) acts within each octonionic block.
        """
        assert anticomm_result['pattern'][0] == "commutes"

    def test_ju_squared_minus_identity(self, J_u):
        """Redundant cross-check: J_u^2 = -I (from Phase 28)."""
        J_sq = J_u @ J_u
        err = np.max(np.abs(J_sq + np.eye(16)))
        assert err < ATOL, f"J_u^2 != -I: max error = {err}"


# ============================================================================
# 4. Grade decomposition tests
# ============================================================================

class TestGradeDecomposition:
    """Tests for Clifford grade decomposition."""

    def test_grade_decomp_identity(self, gamma_matrices):
        """I_{16} should be pure grade-0."""
        result = compute_grade_decomposition(np.eye(16), gamma_matrices)
        assert result['reconstruction_error'] < 1e-13
        assert result['dominant_grade'] == 0
        assert abs(result['coefficients'][frozenset()]) > 0.5
        # No other grades should contribute
        for k in range(1, 5):
            assert result['grade_norms'][k] < ATOL, (
                f"Grade {k} norm = {result['grade_norms'][k]} for identity")

    def test_grade_decomp_gamma(self, gamma_matrices):
        """Each gamma_i should be pure grade-1."""
        for i, g in enumerate(gamma_matrices):
            result = compute_grade_decomposition(g, gamma_matrices)
            assert result['reconstruction_error'] < 1e-13
            assert result['dominant_grade'] == 1, (
                f"gamma_{i+1}: dominant grade = {result['dominant_grade']}")
            for k in [0, 2, 3, 4]:
                assert result['grade_norms'][k] < ATOL, (
                    f"gamma_{i+1}: grade {k} norm = {result['grade_norms'][k]}")

    def test_grade_decomp_commutator(self, gamma_matrices):
        """[gamma_i, gamma_j] = 2 * gamma_i * gamma_j (for i != j) should be pure grade-2."""
        g0, g1 = gamma_matrices[0], gamma_matrices[1]
        comm = g0 @ g1 - g1 @ g0
        # comm = 2 * gamma_0 * gamma_1 (since {g0,g1}=0, so g0*g1 = -g1*g0, comm = 2*g0*g1)
        result = compute_grade_decomposition(comm, gamma_matrices)
        assert result['reconstruction_error'] < 1e-13
        assert result['dominant_grade'] == 2

    def test_grade_decomp_volume(self, gamma_matrices, volume_result):
        """omega = gamma_1*...*gamma_9 = +I, so it should decompose as grade-0 = 1."""
        # omega = +I on this irrep, so it IS the identity
        omega = volume_result['omega']
        result = compute_grade_decomposition(omega, gamma_matrices)
        assert result['reconstruction_error'] < 1e-13
        assert result['dominant_grade'] == 0

    def test_grade_decomp_ju(self, grade_result):
        """J_u grade decomposition: identify dominant grade, verify reconstruction.
        (acceptance test: test-ju-grade-decomp)
        """
        assert grade_result['reconstruction_error'] < 1e-13
        # J_u should have nonzero grades 2 and 3 (mixed grade)
        assert len(grade_result['nonzero_grades']) >= 2
        nonzero_k = [k for k, _ in grade_result['nonzero_grades']]
        assert 2 in nonzero_k, "Grade 2 should be nonzero for J_u"
        assert 3 in nonzero_k, "Grade 3 should be nonzero for J_u"

    def test_grade_norm_sum(self, J_u, grade_result, gamma_matrices):
        """Parseval-like relation: sum of squared coefficient norms = squared total norm / 16.

        Since the Clifford monomials are orthogonal under Tr(A^T B) / 16,
        and we expand M = sum c_S gamma_S, we have:
        Tr(M^T M) / 16 = sum c_S^2 * Tr(gamma_S^T gamma_S) / 16 = sum c_S^2
        (because Tr(gamma_S^T gamma_S)/16 = 1 for each monomial).

        So: ||M||_F^2 / 16 = sum c_S^2 = sum_k ||grade-k-coeffs||^2
        """
        # Sum of squared coefficient norms
        coeff_norm_sq = sum(c**2 for c in grade_result['coefficients'].values())
        # ||J_u||_F^2 / 16
        ju_norm_sq = np.linalg.norm(J_u, 'fro')**2 / 16.0
        rel_err = abs(coeff_norm_sq - ju_norm_sq) / ju_norm_sq
        assert rel_err < 1e-12, (
            f"Parseval mismatch: sum c^2 = {coeff_norm_sq}, ||J_u||^2/16 = {ju_norm_sq}")


# ============================================================================
# 5. J_u depth tests
# ============================================================================

class TestJuDepth:
    """Tests for J_u's membership depth in the associative closure."""

    def test_ju_not_at_depth_0(self, closure_result):
        """J_u is not in the linear span of T_b (confirmed in Phase 28).
        Residual at depth 0 should be > 0.1.
        """
        assert closure_result['ju_residuals'][0] > 0.1, (
            f"J_u residual at depth 0 = {closure_result['ju_residuals'][0]} (too small)")

    def test_ju_not_at_depth_1(self, closure_result):
        """J_u is not in the Lie algebra (46-dim) either.
        Residual at depth 1 should be > 0.1.
        """
        assert closure_result['ju_residuals'][1] > 0.1, (
            f"J_u residual at depth 1 = {closure_result['ju_residuals'][1]} (too small)")

    def test_ju_depth_definite(self, closure_result):
        """J_u enters the closure at a definite depth d where residual
        drops from > 0.1 to < 1e-12.
        (acceptance test: test-ju-depth)
        """
        depth = closure_result['ju_depth']
        assert depth is not None, "J_u never entered closure"
        assert depth >= 2, f"J_u depth = {depth}, expected >= 2"
        # Verify sharp transition
        assert closure_result['ju_residuals'][depth - 1] > 0.1, (
            f"Residual at depth {depth-1} = {closure_result['ju_residuals'][depth-1]} (should be > 0.1)")
        assert closure_result['ju_residuals'][depth] < 1e-12, (
            f"Residual at depth {depth} = {closure_result['ju_residuals'][depth]} (should be < 1e-12)")

    def test_ju_in_final_closure(self, closure_result):
        """At the converged closure (dim 256), J_u membership residual < 1e-12."""
        final_residual = closure_result['ju_residuals'][-1]
        assert final_residual < 1e-12, (
            f"J_u not in final closure: residual = {final_residual}")

    def test_ju_depth_via_wrapper(self, T_matrices, J_u):
        """find_ju_depth returns the same depth as the full closure computation."""
        depth = find_ju_depth(T_matrices, J_u)
        assert depth is not None
        assert depth == 2


# ============================================================================
# 6. Cross-validation
# ============================================================================

class TestCrossValidation:
    """Cross-validation of Clifford structure."""

    def test_clifford_anticommutation_rescaled(self, gamma_matrices):
        """Verify {gamma_i, gamma_j} = 2*delta_{ij}*I for the rescaled generators.

        Redundant with Phase 28 but verifies the rescaling gamma_1 = 4*T_b[1],
        gamma_k = 2*T_b[k] is correct.
        """
        for i in range(9):
            for j in range(i, 9):
                ac = gamma_matrices[i] @ gamma_matrices[j] + gamma_matrices[j] @ gamma_matrices[i]
                if i == j:
                    err = np.max(np.abs(ac - 2.0 * np.eye(16)))
                    assert err < ATOL, (
                        f"{{gamma_{i+1}, gamma_{i+1}}} != 2I: err = {err}")
                else:
                    err = np.max(np.abs(ac))
                    assert err < ATOL, (
                        f"{{gamma_{i+1}, gamma_{j+1}}} != 0: err = {err}")

    def test_closure_basis_orthonormal(self, closure_result):
        """Verify the returned basis is approximately orthonormal."""
        basis = closure_result['basis']  # 256 x 256
        gram = basis.T @ basis
        err = np.max(np.abs(gram - np.eye(gram.shape[0])))
        assert err < 1e-10, (
            f"Basis not orthonormal: max |G - I| = {err}")


# ============================================================================
# 7. Regression
# ============================================================================

class TestPhase28Regression:
    """Verify key Phase 28 results are still intact."""

    def test_T_b_count(self, T_matrices):
        """10 Peirce operators."""
        assert len(T_matrices) == 10

    def test_ju_squared(self, J_u):
        """J_u^2 = -I."""
        err = np.max(np.abs(J_u @ J_u + np.eye(16)))
        assert err < ATOL

    def test_lie_algebra_dim_46(self, T_matrices):
        """Lie algebra dimension = 46."""
        result = compute_commutator_algebra(T_matrices)
        assert result['dimension'] == 46
        assert result['closed']

    def test_ju_outside_span(self, T_matrices, J_u):
        """J_u is not in the linear span of T_b."""
        result = check_ju_in_span(T_matrices, J_u)
        assert not result['in_span']
        assert result['residual'] > 0.1


# ============================================================================
# 8. J_u Clifford polynomial (Plan 02)
# ============================================================================

class TestJuPolynomial:
    """Tests for J_u's explicit Clifford polynomial expression.
    (acceptance test: test-ju-polynomial)
    """

    def test_polynomial_reconstruction(self, gamma_matrices, J_u):
        """The explicit polynomial reconstructs J_u to machine precision."""
        poly = express_ju_as_clifford_polynomial(gamma_matrices, J_u)
        assert poly['reconstruction_error'] < 1e-13, (
            f"Reconstruction error: {poly['reconstruction_error']}")

    def test_polynomial_nonzero_count(self, gamma_matrices, J_u):
        """J_u has exactly 8 nonzero Clifford terms (4 grade-2, 4 grade-3)."""
        poly = express_ju_as_clifford_polynomial(gamma_matrices, J_u)
        assert poly['n_nonzero'] == 8, (
            f"Expected 8 nonzero terms, got {poly['n_nonzero']}")

    def test_polynomial_grade_2_terms(self, gamma_matrices, J_u):
        """Grade-2 terms: subsets {1,8},{2,4},{3,7},{5,6} each with coeff 0.25."""
        poly = express_ju_as_clifford_polynomial(gamma_matrices, J_u)
        g2 = poly['grade_2_terms']
        assert len(g2) == 4
        expected_subsets = {(1, 8), (2, 4), (3, 7), (5, 6)}
        actual_subsets = {s for _, s in g2}
        assert actual_subsets == expected_subsets, (
            f"Grade-2 subsets: {actual_subsets} != {expected_subsets}")
        for c, _ in g2:
            assert abs(c - 0.25) < 1e-12, f"Grade-2 coefficient: {c} != 0.25"

    def test_polynomial_grade_3_terms(self, gamma_matrices, J_u):
        """Grade-3 terms: {0,1,8} with 0.75; {0,2,4},{0,3,7},{0,5,6} with -0.25."""
        poly = express_ju_as_clifford_polynomial(gamma_matrices, J_u)
        g3 = poly['grade_3_terms']
        assert len(g3) == 4
        g3_dict = {s: c for c, s in g3}
        assert abs(g3_dict[(0, 1, 8)] - 0.75) < 1e-12
        for subset in [(0, 2, 4), (0, 3, 7), (0, 5, 6)]:
            assert abs(g3_dict[subset] - (-0.25)) < 1e-12

    def test_polynomial_dominant_term(self, gamma_matrices, J_u):
        """The dominant term is gamma_{018} with coefficient 0.75."""
        poly = express_ju_as_clifford_polynomial(gamma_matrices, J_u)
        c, s = poly['dominant_term']
        assert s == (0, 1, 8), f"Dominant subset: {s} != (0,1,8)"
        assert abs(c - 0.75) < 1e-12, f"Dominant coefficient: {c} != 0.75"

    def test_polynomial_manual_reconstruction(self, gamma_matrices, J_u):
        """Manually reconstruct J_u from the polynomial and verify."""
        poly = express_ju_as_clifford_polynomial(gamma_matrices, J_u)
        reconstruction = np.zeros((16, 16), dtype=np.float64)
        for c, subset in poly['terms']:
            M = np.eye(16, dtype=np.float64)
            for i in subset:
                M = M @ gamma_matrices[i]
            reconstruction += c * M
        err = np.max(np.abs(reconstruction - J_u))
        assert err < 1e-13, f"Manual reconstruction error: {err}"


# ============================================================================
# 9. J_u uniqueness (Plan 02)
# ============================================================================

class TestJuUniqueness:
    """Tests for J_u uniqueness analysis.
    (acceptance test: test-uniqueness)
    """

    def test_uniqueness_norm_squared(self, gamma_matrices, J_u):
        """J_u coefficients have unit norm (sum a_k^2 = 1)."""
        result = test_ju_uniqueness(gamma_matrices, J_u)
        assert abs(result['norm_squared'] - 1.0) < 1e-12, (
            f"Norm squared: {result['norm_squared']} != 1.0")

    def test_uniqueness_constraint_satisfied(self, gamma_matrices, J_u):
        """The nonlinear constraint F(a) = 0 is satisfied at J_u."""
        result = test_ju_uniqueness(gamma_matrices, J_u)
        assert result['constraint_residual'] < 1e-12, (
            f"Constraint residual: {result['constraint_residual']}")

    def test_uniqueness_isolated(self, gamma_matrices, J_u):
        """J_u is an isolated solution (tangent space dimension = 0).

        Within the 8-dim subspace of Clifford monomials appearing in J_u's
        polynomial, J_u is the unique (up to sign) element satisfying X^2 = -I.
        (acceptance test: test-uniqueness)
        """
        result = test_ju_uniqueness(gamma_matrices, J_u)
        assert result['is_isolated'], (
            f"J_u is NOT isolated: tangent_dim = {result['tangent_dim_at_ju']}")

    def test_uniqueness_monomial_count(self, gamma_matrices, J_u):
        """J_u lives in an 8-dimensional monomial subspace."""
        result = test_ju_uniqueness(gamma_matrices, J_u)
        assert result['monomial_subspace_dim'] == 8

    def test_stabilizer_dim_10(self, gamma_matrices, J_u):
        """Stabilizer of J_u in spin(9) has dimension 10."""
        result = test_ju_uniqueness(gamma_matrices, J_u)
        assert result['stabilizer_dim_spin9'] == 10, (
            f"Stabilizer dim: {result['stabilizer_dim_spin9']} != 10")


# ============================================================================
# 10. G_SM commutant (Plan 02)
# ============================================================================

class TestGsmCommutant:
    """Tests for G_SM = Stab_{Spin(9)}(J_u) computation.
    (acceptance test: test-gsm-commutant-dimension)
    """

    def test_commutant_dimension(self, gamma_matrices, J_u):
        """Commutant of J_u in spin(9) has dimension 10 = su(3) + u(1)^2.

        Krasnov predicts dim(G_SM) = 12 = su(3) + su(2) + u(1).
        We find dim = 10. The discrepancy is documented.
        """
        result = compute_gsm_commutant(gamma_matrices, J_u)
        assert result['commutant_dim'] == 10, (
            f"Commutant dim: {result['commutant_dim']} != 10")

    def test_commutant_is_lie_algebra(self, gamma_matrices, J_u):
        """The commutant is closed under brackets (is a Lie subalgebra)."""
        result = compute_gsm_commutant(gamma_matrices, J_u)
        assert result['is_closed']

    def test_semisimple_dim_8(self, gamma_matrices, J_u):
        """The semisimple part has dimension 8 (= su(3))."""
        result = compute_gsm_commutant(gamma_matrices, J_u)
        assert result['semisimple_dim'] == 8, (
            f"Semisimple dim: {result['semisimple_dim']} != 8")

    def test_center_dim_2(self, gamma_matrices, J_u):
        """The center has dimension 2 (= u(1) + u(1))."""
        result = compute_gsm_commutant(gamma_matrices, J_u)
        assert result['center_dim'] == 2, (
            f"Center dim: {result['center_dim']} != 2")

    def test_individual_commuting_generators(self, gamma_matrices, J_u):
        """Exactly 4 individual gamma_i gamma_j commute with J_u."""
        result = compute_gsm_commutant(gamma_matrices, J_u)
        assert result['n_individual'] == 4
        expected = [(1, 8), (2, 4), (3, 7), (5, 6)]
        assert result['individual_commuting'] == expected

    def test_casimir_decomposition(self, gamma_matrices, J_u):
        """R^16 decomposes as 12-dim + 4-dim under the stabilizer."""
        result = compute_gsm_commutant(gamma_matrices, J_u)
        mults = result['casimir_multiplicities']
        mult_values = [m for _, m in mults]
        assert sorted(mult_values) == [4, 12], (
            f"Casimir multiplicities: {mult_values} != [4, 12]")


# ============================================================================
# 11. Spin(10) branching (Plan 02)
# ============================================================================

class TestSpin10Branching:
    """Tests for the Spin(9)->Spin(10) extension analysis.
    (acceptance test: test-spin10-branching, test-all-10-anticommutation,
     test-complexification-structure)
    """

    def test_case_b(self, gamma_matrices, J_u):
        """J_u is Case B: does NOT anticommute with all gamma_i.
        (acceptance test: test-all-10-anticommutation)
        """
        result = verify_spin10_branching(gamma_matrices, J_u)
        assert result['case'] == 'B'

    def test_span_dim_45(self, gamma_matrices, J_u):
        """span{spin(9), gamma_i J_u} has dimension 45."""
        result = verify_spin10_branching(gamma_matrices, J_u)
        assert result['span_dim_45'] == 45, (
            f"Span dim: {result['span_dim_45']} != 45")

    def test_not_lie_algebra(self, gamma_matrices, J_u):
        """The 45-dim space is NOT a Lie algebra (not closed under brackets)."""
        result = verify_spin10_branching(gamma_matrices, J_u)
        assert not result['is_lie_algebra'], (
            "Expected NOT a Lie algebra, but it is")

    def test_generated_lie_dim_255(self, gamma_matrices, J_u):
        """The generated Lie algebra has dim 255 = sl(16, R).

        Since J_u is antisymmetric and gamma_i are symmetric, the products
        gamma_i J_u are antisymmetric (= traceless). Their iterated commutators
        generate sl(16, R), not the expected so(10) or spin(10).
        """
        result = verify_spin10_branching(gamma_matrices, J_u)
        assert result['generated_lie_dim'] == 255, (
            f"Generated Lie dim: {result['generated_lie_dim']} != 255")
        assert result['generated_lie_type'] == "sl(16, R)"

    def test_complexification_valid(self, gamma_matrices, J_u):
        """J_u defines a valid complex structure on R^16 (J_u^2 = -I).
        (acceptance test: test-complexification-structure)
        """
        result = verify_spin10_branching(gamma_matrices, J_u)
        assert result['complexification_valid']

    def test_j_linear_dim_10(self, gamma_matrices, J_u):
        """The J_u-linear subalgebra of spin(9) has dim 10 = stab(J_u)."""
        result = verify_spin10_branching(gamma_matrices, J_u)
        assert result['j_linear_dim'] == 10

    def test_j_linear_is_subalgebra(self, gamma_matrices, J_u):
        """The J_u-linear elements form a Lie subalgebra."""
        result = verify_spin10_branching(gamma_matrices, J_u)
        assert result['j_linear_is_subalgebra']
